service: taskmanagement-apis
frameworkVersion: '>=1.28.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}

functions:
  CreateProject:
    handler: bin/taskmanagementapp/main
    events:
      - http:
          path: /createProject
          method: POST
  HealthCheck:
    handler: bin/taskmanagementapp/main
    events:
      - http:
          path: /healthCheck
          method: GET
  
package:
  patterns:
    - '!*/**'
    - bin/**

plugins:
  - serverless-offline
 
custom:
  serverless-offline:
    noPrependStageInUrl: true


